
version: '2'

services:

  db:
    image: mdillon/postgis:9.5
    networks:
      - back-tier
    volumes:
      - pg-data:/var/lib/postgresql/data

  web:
    image: node
    networks:
      - back-tier
    expose:
      - "3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: ["node", "app"] #/usr/local/bin/gunicorn -w 2 -b :8000 app:app

volumes:
  pg-data:
    driver: local

networks:
  back-tier:
    driver: bridge

